import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import FireFilesBackground from "@/components/FireFilesBackground";
import Sound from "@/components/Sound";

// Inter => user form text.
const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={clsx(
					inter.variable,
					"bg-background text-foreground font-inter"
				)}
			>
				<FireFilesBackground />
				<Sound />
				{children}
				<div id='my-modal'/>
			</body>
		</html>
	);
}
